### ISSUE TITLE
Parse VSCode-vars in config

### ISSUE THREAD

**Issue by dkuschmierz** [cschlosser/doxdocgen#110]
# Description

Replace the VSCode-internal variables with their value instead writing the variabel as text.

## Code example

```Cpp
"doxdocgen.generic.authorName": "${env:USERNAME}",
```

### Expected result

```Cpp
/**
 * @author USERNAME
 */
```

### Actual result

```Cpp
/**
 * @author ${env:USERNAME}
 */
```

**Comment by cschlosser** [comment]
We could parse actual env vars but I couldn't find a way to access the VS Code internal ones.
Would this be fine as well?

**Comment by dkuschmierz** [comment]
Yes sure, actually this is an environment-variable from system...
