### ISSUE TITLE
Files without includes don't trigger the autocomplete for file description

### ISSUE THREAD

**Issue by rodrigoA** [cschlosser/doxdocgen#141]
# Description

1. Create a .h file and declare a class. Note: This file should not contain any include
2. Insert two new blank lines between class declaration and line 1
3. At the first line of the file type: /** and hit enter.
4. The result is an autocomplete doc for the Class, not for the file

Obs: **_version 0.5.2_**

## Code example

```Cpp
class Foo {
Foo() {};
}
```

### Expected result

```Cpp
/**
 * @file <>.h
 * @author 
 * @brief 
 * @date 
 *  
 */

class Foo {
Foo() {};
}
```

### Actual result

```Cpp
/**
 * @brief 
 * 
 */

class Foo {
Foo() {};
}
```

**Comment by christophschlosser** [comment]
This is actually the expected behavior because that's what you told the addon to do.
I.e. seach (by default 20) lines until you find something. I can see why this seems unexpected to you. Mabye I will have to deal with this in another way.
