### ISSUE TITLE
Can't show more items after changing doxdocgen.generic.order

### ISSUE THREAD

**Issue by chenshuqu** [cschlosser/doxdocgen#143]
# Description

i want to generate date and author on function comment, and add something like below, but i can't see anything happen.

## Code example

   // The order to use for the comment generation. Values can be used multiple times. Valid values are shown in default setting.
   "doxdocgen.generic.order": [
    "brief",
    "param",
    "return",
    "date",
    "author",
  ]

### Expected result

/**
 * @brief demo
 * @input a
 * @input b
 * @return c 
 * @date 2019-12-09
 * @author foo@foo.com
 */

### Actual result

/**
 * @brief demo
 * @input a
 * @input c
 * @return c 
 */

**Comment by christophschlosser** [comment]
As you can see in the documentation only these values are valid for functions:
```json
"brief",
"empty",
"tparam",
"param",
"return"
```

**Comment by chenshuqu** [comment]
@christophschlosser  Thanks for your reply.

May i ask what it is the concern that constrains the values for the function?

It seems like without such a constrain, it would be more flexible.

**Comment by christophschlosser** [comment]
There simply was no need before to support the tags which are usually only used in `file` comments for `functions` as well.

**Comment by HO-COOH** [comment]
@chenshuqu Since `1.2.2`, most tags are available in both functions and file comments. Now you can use `date` and `author` in `generic. order`

@cschlosser This can be closed.
