### ISSUE TITLE
The empty line

### ISSUE THREAD

**Issue by mcakircali** [cschlosser/doxdocgen#181]
# Description

e.g., the functions without parameters has a redundant ```@empty``` line after ```@brief```. 

### Expected result

```Cpp
/**
 * @brief 
 */
```

### Actual result

```Cpp
/**
 * @brief 
 * I don't need this (empty) line
 */
```

# Feature Request

Is it possible drop the ```@empty``` from the order for such cases?

**Comment by cschlosser** [comment]
Probably. Will have to look into why the empty line is there

**Comment by HO-COOH** [comment]
@mcakircali Add this setting in your `settings.json` (delete the `empty` tag in the default order)
```json
    "doxdocgen.generic.order":[
        "brief",
        "tparam",
        "param",
        "return",
        "custom"
    ]
```
And it should work as you expected. @cschlosser  This can be closed.
