### ISSUE TITLE
How to set doxdocgen.generic.authorEmail to "git config --get user.email"

### ISSUE THREAD

**Issue by Archiatrus** [cschlosser/doxdocgen#182]
Basically title. We use one common checked in vscode settings file.
I found `${env:}` but this is not an environment variable.
I also found `${command:}` but I have no idea what to write as commandId.

Any idea if this is possible at all?

**Comment by Archiatrus** [comment]
It seems `${command:}` [will never work](https://github.com/microsoft/vscode/issues/102414) within settings :( Then I assume it has to be an option within doxdocgen.

Feature request:

- option to substitute `{author}` with `git config --get user.name`
- option to substitute `{email}` with `git config --get user.email`

**Comment by cschlosser** [comment]
Should in theory be possible with `child_process`.
Would have to be implemented carefully though because this may lead to long running operations (e.g. git for windows is often quite slow) which in turn would lead to empty messages or bad response times of the add-on.
