### ISSUE TITLE
How to add own content in the template?

### ISSUE THREAD

**Issue by magusikrak** [cschlosser/doxdocgen#193]
Like I want  "@subject" and "@tutor" to appear alongside the others. How do I do that?

**Comment by cschlosser** [comment]
```json
  // The order to use for the comment generation. Values can be used multiple times. Valid values are shown in default setting.
  "doxdocgen.generic.order": [
    "brief",
    "empty",
    "tparam",
    "param",
    "return",
    "custom"
  ],

  // Custom tags to be added to the generic order. One tag per line will be added. You have to specify the prefix yourself.
  "doxdocgen.generic.customTags": [],
```

So 
```json
"doxdocgen.generic.customTags": [
  "@subject",
  "@Tutor"
],
```

fo your

**Comment by magusikrak** [comment]
I did exactly as you asked. But custom tags only appear anywhere except the top of the file. 
I want those tags with the  ``` "doxdocgen.file.fileOrder": [ ], ``` . Insted those appear with the generic order elements like parameters, etc. <br>
I want the tags to appear like this.
![image](https://user-images.githubusercontent.com/51502114/102307957-abc9cd80-3f8d-11eb-8afc-89c12b3527f5.png)
<br>
Not like this:
![image](https://user-images.githubusercontent.com/51502114/102307998-c439e800-3f8d-11eb-8145-f512506fa5bd.png)

**Comment by cschlosser** [comment]
What is the content of your `"doxdocgen.file.fileOrder"`?
Could you maybe even post all your doxdocgen settings?

**Comment by magusikrak** [comment]
I had to add "custom" in <br>
```
 "doxdocgen.file.fileOrder": [
    "file",
    "author",
    "brief",
    "version",
    "date",
    "empty",
    "copyright",
    "empty",
    "custom"
  ]
```
and add my tags in ``` "doxdocgen.file.customTag": ["@subject","@tutor"] ``` in the same pattern as you mentioned. :)
