### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by BillDenton** [cschlosser/doxdocgen#202]
- Issue Type: `Bug`
- Extension Name: `doxdocgen`
- Extension Version: `1.1.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.52.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 916,
		"activateCallTime": 1,
		"activateResolvedTime": 89,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "cschlosser.doxdocgen",
				"_lower": "cschlosser.doxdocgen"
			},
			"activationEvent": "onLanguage:cpp"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Illegal value for `line`"
		}
	]
}
```

**Comment by cschlosser** [comment]
Can you provide more detail where/when this is happening?

**Comment by eeliu** [comment]
Me too

![image](https://user-images.githubusercontent.com/27064129/153345008-5b14a2f4-2685-4cbd-9b54-582853de761f.png)

**Comment by cschlosser** [comment]
Seems to me more like a problem with a broken extension locally and VS Code.
Reinstalls shouldn't fix this kind of bug.
