### ISSUE TITLE
@return where it shouldn't

### ISSUE THREAD

**Issue by NikLeberg** [cschlosser/doxdocgen#210]
# Description

If I disable the type for returns with `"doxdocgen.generic.includeTypeAtReturn": false` a @return is added where it shouldn't.
(I have Version 1.1.0)

## Code example

```Cpp
struct {
    int bar;
} foo;
```

### Expected result

```Cpp
/**
 * @brief 
 * 
 */
```

### Actual result

```Cpp
/**
 * @brief 
 * 
 * @return  
 */
```

**Comment by cschlosser** [comment]
Should be fixed in 1.2.1
