### ISSUE TITLE
Fill in of Brief title content

### ISSUE THREAD

**Issue by bob2oneil** [cschlosser/doxdocgen#226]
Is there any particular setting the enables filling in of the @brief content?

**Comment by cschlosser** [comment]
Are you referring to this: https://github.com/cschlosser/doxdocgen#smart-text ?

**Comment by hideogump** [comment]
I am referring to the @brief Doxygen field itself.  Using an IDE such as QtCreator, this content gets filled in automatically.

For example:

/**
 * @brief config::temp
 * @param arg
 */
void config::temp(const char* arg)
{
    
}

**Comment by cschlosser** [comment]
We can think about some customization that will be put into the `@brief` command.

Please use markdown code tags ``` so random user's aren't notified by you `@mentioning` them.

**Comment by bob2oneil** [comment]
Thanks.
