### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Anisha123-hub** [cschlosser/doxdocgen#238]
- Issue Type: `Bug`
- Extension Name: `doxdocgen`
- Extension Version: `1.3.2`
- OS Version: `Windows_NT x64 6.2.9200`
- VS Code version: `1.56.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by cschlosser** [comment]
Sorry, this is missing all the information.

**Comment by cschlosser** [comment]
Feel free to reopen if you have more information
