### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by mchernov-intel** [cschlosser/doxdocgen#239]
I couldn't realize how to use it and didn't found any info about this.

**Comment by cschlosser** [comment]
What exactly is causing a problem for you?
Are you having a hard time to install the plugin or can I help you with something else?

**Comment by dr3adl0rd** [comment]
There's no information about which languages are supported anywhere, and not everyone knows it's only C and C++, so putting that little detail in the Readme would actually save many people trial and error!

**Comment by cschlosser** [comment]
Sorry, I have to disagree with you:

<img width="318" alt="Bildschirmfoto 2021-07-31 um 22 10 47" src="https://user-images.githubusercontent.com/2466365/127751400-0e85f630-bdda-47dc-af75-a776fd2ab9dc.png">
<img width="1036" alt="Bildschirmfoto 2021-07-31 um 22 11 05" src="https://user-images.githubusercontent.com/2466365/127751401-a5bb8ca6-9d97-4184-b936-7333201295bb.png">

It's prominently displayed on repository page and the official addon listing.

**Comment by dr3adl0rd** [comment]
Not sure why is it a problem to add C and C++ to the title in the marketplace? Here's a screenshot of the addon from the marketplace, where there's no info about C or C++ anywhere.
![Screenshot 2021-07-31 215117](https://user-images.githubusercontent.com/12574646/127752198-d7e44e45-fef3-46aa-b83e-e2e5f48d1d22.png)

**Comment by cschlosser** [comment]
If you have a request for this addon please open an issue and don't hijack other peoples issues.
I would also like to point out to you that your (passive) aggressive behavior will no longer be tolerated.

If you're unhappy with how VSCode presents information from the marketplace please file a feature request with Microsoft on their repository.

**Comment by dr3adl0rd** [comment]
I was only suggesting a name change to make it clearer for people to know what it does. I have no idea why you are so aggressive - I have no interest in hijacking anything, only wanted to help, but I guess I will just ignore you instead, I guess you just can't take it when people are openly pointing out your mistakes.
Goodbye and good luck.

**Comment by cschlosser** [comment]
This issue was from a user who couldn't make the addon work and you suggest changing the name of the addon.

For me this is unrelated and instead of following my request to open a dedicated issue you're assuming the victim role and want to twist it to make it look like it's something personal now.
The closed issues in this repository also speak a different language than what you're suggesting.
