### ISSUE TITLE
Extensive customization , how can I trigger ?

### ISSUE THREAD

**Issue by wangwenqiangGitHub** [cschlosser/doxdocgen#241]
# Description
how can i trigger "///"
Anything you'd like to add

## Code example

```Cpp
// Put your code here
```

### Expected result

```Cpp
/**
 * @brief Put the expected comment here
 */
```

### Actual result

```Cpp
/**
 * @brief Put the actually generated comment here
 */
```

**Comment by cschlosser** [comment]
Set `"doxdocgen.c.triggerSequence"` to `///`.
It defaults to `"/**"`.

**Comment by ChenYCL** [comment]
doxdocgen.c.triggerSequence": "/**" , not working on *.tsx

**Comment by cschlosser** [comment]
Thank you for the video.
This addon currently only supports C and C++.
If the language you're using is not listed [here](https://github.com/cschlosser/doxdocgen/issues?q=is%3Aissue+label%3A%22new+languge%22+) feel free to create a new issue for it.

Contributions are always welcome and you can provide implementation for a language that is missing currently.
