### ISSUE TITLE
Question About Custom File Tag Syntax

### ISSUE THREAD

**Issue by TallKoala** [cschlosser/doxdocgen#243]
I'm trying to figure out the syntax required to generate two more custom file tags named input and output, but I can't seem to make it work. This is what I have tried. I can't figure out what I'm missing. 

"doxdocgen.generic.customTags":["Input: {input},", "Output: {output}"],
    "doxdocgen.file.fileOrder": [
        "file",
        "author",
        "date",
        "brief",
        "input",
        "output",
    ],

Any help would be greatly appreciated!

**Comment by cschlosser** [comment]
Please take a close look at the documentation:

1. Can template `{year}`, `{date}`, `{author}`, `{email}` and `{file}`
2. You have to specify the prefix.

You can try it with this configuration but note from 1. that `input` and `output` won't be magically replaced.

```json
"doxdocgen.generic.customTags":["@Input: {input},", "@Output: {output}"],
"doxdocgen.file.fileOrder": [
"file",
"author",
"date",
"brief",
"custom",
],
```

**Comment by TallKoala** [comment]
Got it! I actually don't need to template Input and Output since they will change from file to file. It's working now! Thanks for the help, and making such a rad extension.
