### ISSUE TITLE
\param and \return not generated for method

### ISSUE THREAD

**Issue by LostInCompilation** [cschlosser/doxdocgen#247]
When creating a doxygen comment for the method in a header file, param and return wont get generated for Foo(). However generations works on the above static function. and in the defining cpp file.
All settings for the plugin are on default, tried reinstalling it.
What should I do?

```
namespace A::B
{
	class DP_API MyClass
	{
	private:
		static HMODULE DLLModule;

		MyClass() {}

	public:
		/**
		 * Desc.
		 * 
		 * \param dllModule
		 */
		static void SetDLLModule(HMODULE dllModule) { DLLModule = dllModule; }

		/**
		 * Desc.
		 */
		bool Foo(HMODULE aValue);
};
```

**Comment by cschlosser** [comment]
Hi @LostInCompilation ,

I'm sorry that you're experiencing these issues.

Could you please provide a screencap of what you're doing?

Currently I can not reproduce your problem:

https://user-images.githubusercontent.com/2466365/126681731-dfc8d623-852c-4b03-a055-5f0cd1e3949e.mov

**Comment by LostInCompilation** [comment]
Thanks for testing. Well now it is working for me too after two days of normal development...
Do you request the function signature somehow from VisualStudio/IntelliSense for generating the comments? Maybe my IntelliSense was broken because I'm not able to reproduce the error now.

**Comment by cschlosser** [comment]
No, the file is parsed as text.
The addon not working is ususally the case when VSCode detects the wrong language of the file but working on one method and not the other is very strange.

I will close this for now, feel free to open a new issue if you experience any further issues.
