### ISSUE TITLE
未知-未捕获的错误

### ISSUE THREAD

**Issue by xyz-99-thinker** [cschlosser/doxdocgen#251]
**Describe the bug**
Error: spawn git ENOENT at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19) at onErrorNT (internal/child_process.js:465:16) at processTicksAndRejections (internal/process/task_queues.js:80:21)
**Screencaps**
![image](https://user-images.githubusercontent.com/58734389/129766719-a6d91c37-d842-46d6-a5d2-44e9f42af970.png)

**Your System:**
 - OS:windows10
 - VS Code 1.59

**Additional context**
使用正常，但会引发其他未知错误，譬如错误的报错提示。

**Comment by cschlosser** [comment]
Hi,
can you please provide additional information in english?
I don't see how this relates to this addon from the screenshot and I can't read Chinese

**Comment by xyz-99-thinker** [comment]
When I installed the plug-in this message popped up, so far except for the occurrence of lag, the plug-in can be used normally, and I do not know what caused this
<img width="679" alt="屏幕截图 2021-08-20 214349" src="https://user-images.githubusercontent.com/58734389/130242712-4da15252-81c0-4fc1-a8c3-1474c9f88b27.png">

**Comment by cschlosser** [comment]
>I apologize for not replying in time

No problem, don't worry :)

> When I installed the plug-in this message popped up, so far except for the occurrence of lag, the plug-in can be used normally, and I do not know what caused this

Thank you. Do you have git installed on your system?

**Comment by xyz-99-thinker** [comment]
> > 我为没有及时回复表示歉意
> 
> 没问题，别担心:)
> 
> > 我安装插件的时候弹出这个提示，目前除了出现卡顿现象，插件都可以正常使用，不知道是什么原因造成的
> 
> 谢谢。你的系统上安装了git吗？

**Comment by xyz-99-thinker** [comment]
No, I should not have installed it.

**Comment by xyz-99-thinker** [comment]
No, I should not have installed it.

**Comment by cschlosser** [comment]
Ok. thank you for responding.
Then it's probably because the addon tried to detect your `author` and `email` from git.

**Comment by xyz-99-thinker** [comment]
OK，You're right(I think so...but I don`t want to install it). 
Thanks.

**Comment by TheRolfFR** [comment]
Hello,

Could it be possible to reopen the issue and really fix that problem ?
I can't install git and the fallback value should be the settings value.

Could you add it as an option in the extension settings too?

Thanks!
