### ISSUE TITLE
generator does not trigger for '.h' files that have cuda code in them

### ISSUE THREAD

**Issue by boanergies** [cschlosser/doxdocgen#261]
**Describe the bug**
So I'm working with code where we label header files that have cuda syntax such as `__device__` to have the file extension `.h`. When I try to trigger the documentation generator it doesn't run, as soon as I change the file extension to `.cuh` it suddenly works. My feeling is this is a bug but I also understand if this is just the fact that the generator treats `.h` files as c++ and `.cuh` as cuda and treats `__device__` as an error in a `.h` file.

Is it possible to treat `.h` files as either cuda or c++?

**My System:**
 - OS: Linux
 - VS Code Version 1.62.3
 - Doxdocgen Code Version 1.3.2

**Comment by cschlosser** [comment]
Hi @boanergies ,

the generator should not differentiate between c, cpp or cuda: https://github.com/cschlosser/doxdocgen/blob/9c8c583a95c99656aeff23d33d0ca422f55bad0a/src/CodeParserController.ts#L104

Does VS Code detect the language correctly when you have set it to `.h`?

**Comment by boanergies** [comment]
Reading [this](https://github.com/cschlosser/doxdocgen/pull/273) as part of the most recent release my issue may be connected to it. I'll try again and see what happens.

**Comment by boanergies** [comment]
sorry it took me awhile to comment back on this, I tested it this morning and it seems to be working. Thank you for all your hard work this is such a great extension
