### ISSUE TITLE
in my it is showing go live is irresponsive Extension issue

### ISSUE THREAD

**Issue by Vinayakams67** [cschlosser/doxdocgen#271]
- Issue Type: `Bug`
- Extension Name: `doxdocgen`
- Extension Version: `1.3.2`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.62.3`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by cschlosser** [comment]
Hi @Vinayakams67 ,

does this issue still persist for you?

**Comment by Vinayakams67** [comment]
Hi Cschlosser/Doxdocgen
Now it is working fine.
Thank you very much ❤️

**Comment by Vinayakams67** [comment]
Thanks a lot. ❤️
