### ISSUE TITLE
doxdocgen.generic.dateFormat for DDD doesn't works

### ISSUE THREAD

**Issue by lchagnoleau** [cschlosser/doxdocgen#286]
**Describe the bug**
When I set the settings : ```"doxdocgen.generic.dateFormat": "DDD, MMM DD YYYY"```, I obtain something like ```103, Apr 13 2022``` instead of ```Wed, Apr 13 2022```

**Code example**

```C
/**
 *  \file    main.c
 *  \brief   
 *
 *  \author  Me
 *
 *  \version 
 *  \date    103, Apr 13 2022
 */
```

**Comment by cschlosser** [comment]
Hi @lchagnoleau ,

Unfortunately for you this works as intended: https://momentjscom.readthedocs.io/en/latest/moment/04-displaying/01-format/
I'm using momentjs for parsing dates and this is the format they chose.

To achieve what you're looking for try with lowercase `ddd`.
